# Travis Continuous Integration Configuration File
language:
  - cpp
compiler:
  - gcc
notifications:
  email:
    recipients:
      - miquel.massot@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always
before_install:
  - sudo apt-add-repository --yes ppa:boost-latest/ppa
  - sudo apt-get update
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

install:
  - sudo apt-get install --yes g++ clang libboost-all-dev cmake
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - mkdir -p build
  - cd build
  - cmake ..
  - make
after_success:
- openssl aes-256-cbc
  -K $encrypted_dc9ab2986818_key
  -iv $encrypted_dc9ab2986818_iv
  -in  config/travisci_rsa.enc
  -out config/travisci_rsa
  -d
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- sudo apt-get install doxygen graphviz
- openssl aes-256-cbc
  -K  $encrypted_dc9ab2986818_key
  -iv $encrypted_dc9ab2986818_iv
  -in config/travisci_rsa.enc
  -out config/travisci_rsa
  -d
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- ./config/publish-doxygen
